name: Daily Commit

# Har kuni ishga tushadi
on:
  schedule:
    - cron: '0 0 * * *' # UTC 00:00
  workflow_dispatch: # Qo'lda ishga tushirish opsiyasi ham mavjud

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Butun tarixni olish

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "Developer-Mustafo"
          git config user.email "mustaforahimov30@gmail.com"

      - name: Run script
        run: node index.js

      - name: Push changes
        run: |
          git push origin main
